---
abstract: 'Prepend lines at the top of your perl files'
author:
  - 'Jerome Quelin'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::Deep: '0'
  Test::More: '0.88'
  blib: '1.01'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Prepender
provides:
  Dist::Zilla::Plugin::Prepender:
    file: lib/Dist/Zilla/Plugin/Prepender.pm
    version: '2.004'
requires:
  Dist::Zilla::Role::FileMunger: '0'
  Moose: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  IRC: irc://irc.perl.org/#distzilla
  MailingList: http://dzil.org/#mailing-list
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Prepender
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Prepender/
  repository: git://github.com/karenetheridge/Dist-Zilla-Plugin-Prepender.git
version: '2.004'
x_Dist_Zilla:
  perl:
    version: '5.025010'
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          $Dist::Zilla::Role::Bootstrap::VERSION: '1.001003'
          distname: Dist-Zilla-Plugin-Prepender
          fallback: '1'
          try_built: '1'
          try_built_method: mtime
      name: Bootstrap::lib
      version: '1.001002'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: 0
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.0
          repo_root: .
      name: '@Author::JQUELIN/Git::NextVersion'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
      name: '@Author::JQUELIN/GatherDir'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: test
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Author::JQUELIN/Test::Compile'
      version: '2.056'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::JQUELIN/PodCoverageTests'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::JQUELIN/PodSyntaxTests'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::JQUELIN/Test::ReportPrereqs'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::JQUELIN/PruneCruft'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::JQUELIN/PruneFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::JQUELIN/ManifestSkip'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::JQUELIN/AutoPrereqs'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::JQUELIN/ExtraTests'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::JQUELIN/NextRelease'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::JQUELIN/PkgVersion'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.015'
      name: '@Author::JQUELIN/PodWeaver'
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::JQUELIN/Prepender'
      version: '2.004'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::JQUELIN/ExecDir'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::JQUELIN/ShareDir'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::JQUELIN/Bugtracker'
      version: '1.111080'
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Author::JQUELIN/Homepage'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::JQUELIN/Repository'
      version: '0.20'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::JQUELIN/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.009'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002003'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000033'
          version: '0.004'
      name: '@Author::JQUELIN/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::JQUELIN/MetaConfig'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: '@Author::JQUELIN/HelpWanted'
      version: 0.3.1
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::JQUELIN/License'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Covenant
      name: '@Author::JQUELIN/Covenant'
      version: 0.1.1
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::JQUELIN/MetaYAML'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::JQUELIN/MetaJSON'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::JQUELIN/ModuleBuild'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::JQUELIN/Readme'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Author::JQUELIN/ReadmeAnyFromPod'
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::JQUELIN/Manifest'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::JQUELIN/CheckChangeLog'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::JQUELIN/TestRelease'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README.mkdn
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.0
          repo_root: .
      name: '@Author::JQUELIN/Git::Check'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README.mkdn
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::JQUELIN/Git::Commit'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: v2.004
          tag_format: v%v
          tag_message: v%v
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::JQUELIN/Git::Tag'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.0
          repo_root: .
      name: '@Author::JQUELIN/Git::Push'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::JQUELIN/UploadToCPAN'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.009'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::JQUELIN/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.009'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.009'
x_author_pledge:
  version: 1
x_serialization_backend: 'YAML::Tiny version 1.72'
